//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub account_id: Option<String>,
    pub last_seen: DateTime,
    pub last_height: i64,
    pub last_hash: String,
    pub agent_name: String,
    pub agent_version: String,
    pub agent_build: String,
    pub peer_count: i64,
    pub is_validator: bool,
    pub status: String,
    pub bandwidth_download: i64,
    pub bandwidth_upload: i64,
    #[sea_orm(column_type = "Float")]
    pub cpu_usage: f32,
    pub memory_usage: i64,
    pub boot_time_seconds: i64,
    #[sea_orm(column_type = "Double")]
    pub block_production_tracking_delay: f64,
    #[sea_orm(column_type = "Double")]
    pub min_block_production_delay: f64,
    #[sea_orm(column_type = "Double")]
    pub max_block_production_delay: f64,
    #[sea_orm(column_type = "Double")]
    pub max_block_wait_delay: f64,
    pub chain_id: Option<String>,
    pub protocol_version: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
